---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r, message=FALSE}
library(plyr)
library(dplyr)
```

```{r}
OriginalData <- read.csv("activity.csv", na.strings = "NA")
head(OriginalData, 10)
```
---

## What is mean total number of steps taken per day?

```{r}
daysdata <- group_by(OriginalData, date)
sumdata1 <- summarise(daysdata, sum(steps, na.rm=TRUE))
colnames (sumdata1) <- c("date","Total")
hist(sumdata1$Total, breaks=60, main = "Histogram of Total Steps per day", xlab = "Total Steps per Day")

```

``` {r}
MeanSteps <- mean(sumdata1$Total, na.rm=TRUE)
MedianSteps <- median(sumdata1$Total, na.rm=TRUE)
OutMessage1 <- paste("Mean Steps = ", MeanSteps, "  Median of Steps = ",MedianSteps)
OutMessage1
```


## What is the average daily activity pattern?

```{r}
intervaldata <- group_by(OriginalData, interval)
sumdata2 <- summarise(intervaldata, mean(steps, na.rm=TRUE))
colnames (sumdata2) <- c("Interval","Average")

plot(sumdata2$Interval,sumdata2$Average, type = "l", xlab = "Time Intervals", ylab = "Average Steps", main = "Average Steps per Interval")
```

```{r}
MaxStepsInterval <- sumdata2$Interval[which.max(sumdata2$Average)]
MaxIntervalOutMessage <- paste("Maximum Average Steps Occurs at Time Interval ", MaxStepsInterval)
MaxIntervalOutMessage
```


## Imputing missing values

```{r}
NumberOfNA <- nrow(OriginalData[is.na(OriginalData$steps),])
NumberOfNAMessage <- paste(" The Number of rows with NAs are = ",NumberOfNA)
NumberOfNAMessage
```

```{r}
daysdata2 <- group_by(OriginalData, date)
sumdata3 <- summarise(daysdata2, mean(steps, na.rm=TRUE))
colnames (sumdata3) <- c("date","MeanSteps")
NewImputedData <- OriginalData
sumdata3[,"MeanSteps"] <- round(sumdata3$MeanSteps)
NewImputedData[,"steps"] <- sumdata3$MeanSteps
```

```{r}
daysdata5 <- group_by(NewImputedData, date)
sumdata5 <- summarise(daysdata5, sum(steps, na.rm=TRUE))
colnames (sumdata5) <- c("date","Total")
hist(sumdata5$Total, breaks=60, main = "Histogram of Total Steps per day with Imputed Data", xlab = "Total Steps per Day")

```


``` {r}
MeanSteps2 <- mean(sumdata5$Total, na.rm=TRUE)
MedianSteps2 <- median(sumdata5$Total, na.rm=TRUE)
OutMessage3 <- paste("Mean Steps with Imputed Data = ", MeanSteps2, "  Median of Steps = ",MedianSteps2)
OutMessage3
```
## Are there differences in activity patterns between weekdays and weekends?

```{r}
NewImputedData[,"Weekday"] <-  weekdays(as.Date(NewImputedData$date))

##NewImputedWDData <- subset(NewImputedData,,(Weekday != c("Sunday","Saturday")),"steps","date","interval")
NewImputedWDData <- NewImputedData

##NewImputedWEData <- subset(NewImputedData,,(Weekday == c("Sunday","Saturday")),"steps","date","interval")
NewImputedWEData <- NewImputedData
##head(NewImputedWeekEndData,10)
plot(NewImputedWDData$steps,NewImputedWDData$interval, type = "l", xlab = "Interval", ylab = "Number of Steps", main = "Steps per Interval")

```
